wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.16
    cli_version: 0.14.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1681324119.449793
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 1
      - 23
      4: 3.8.16
      5: 0.14.2
      8:
      - 5
batch_size:
  desc: null
  value: 64
test_batch_size:
  desc: null
  value: 1000
epochs:
  desc: null
  value: 14
lr:
  desc: null
  value: 1.0
gamma:
  desc: null
  value: 0.7
no_cuda:
  desc: null
  value: false
no_mps:
  desc: null
  value: false
dry_run:
  desc: null
  value: false
seed:
  desc: null
  value: 1
log_interval:
  desc: null
  value: 10
save_model:
  desc: null
  value: false
